// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xicyeywezoqfcpnkjxaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpY3lleXdlem9xZmNwbmtqeGFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODM4NjEsImV4cCI6MjA2Njg1OTg2MX0.VmBQPLEot_dUlosuxYra_XYza8yL23oSigF40UFVsis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});